name: Continuous-Integration
on:
  workflow_run:
    workflows:
      - Bump-Semantic-Version
    types:
      - completed

jobs:
  continuous-integration-build:
    name: Continuous Integration Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: 'Get Current tag'
      id: currenttag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0 # Optional fallback tag to use when no tag can be found
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./DotNetNinja.AutoBoundConfiguration.sln
    - name: Build
      run: dotnet build ./DotNetNinja.AutoBoundConfiguration.sln -c Release --no-restore -p:Version=${{ steps.currenttag.outputs.tag }}
    - name: Test
      run: dotnet test ./DotNetNinja.AutoBoundConfiguration.sln -c Release --no-build --verbosity normal
    - name: Package Artifacts
      run: dotnet pack ./src/DotNetNinja.AutoBoundConfiguration/DotNetNinja.AutoBoundConfiguration.csproj -p:PackageVersion=${{ steps.currenttag.outputs.tag }} -c Release 
    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DotNetNinja.AutoBoundConfiguration
        path: ./src/DotNetNinja.AutoBoundConfiguration/bin/release/*.nupkg
        